baseURL = 'https://shoutsky.com/'
languageCode = 'en-us'
title = 'Skylar Houghton'
theme = 'hugo-theme-relearn'

[[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"
    disable=false